# Creating a pandas Data Frame

In [1]:
import numpy as np
import pandas as pd

In [2]:
d = {'x': [1, 2, 3], 'y': [2, 4, 8], 'z': 100}

df = pd.DataFrame(d)

In [3]:
df2 = pd.DataFrame(d, index=[100, 200, 300], columns=['z', 'y', 'x'])

df2

       z  y  x
100  100  2  1
200  100  4  2
300  100  8  3

In [4]:
student_dict = {
    'Name': ['Joe', 'Nat', 'Harry'],
    'Age': [20, 21, 19],
    'Marks': [85.10, 77.80, 91.54]
}

student_df = pd.DataFrame(student_dict)

student_df.head()
student_df.dtypes

Name         str
Age        int64
Marks    float64
dtype: object

In [5]:
student_df = student_df.set_index('Name')

print(student_df.head())

       Age  Marks
Name
Joe     20  85.10
Nat     21  77.80
Harry   19  91.54

In [6]:
data = {
    'Product': ['Laptop', 'Tablet', 'Phone'],
    'Price': [1200, 300, 800],
    'Quantity': [50, 150, 100]
}
df3 = pd.DataFrame(data)

df3.head()

  Product  Price  Quantity
0  Laptop   1200        50
1  Tablet    300       150
2   Phone    800       100

In [7]:
df3.index = pd.RangeIndex(start=1, stop=4, step=1)

df3.head()

  Product  Price  Quantity
1  Laptop   1200        50
2  Tablet    300       150
3   Phone    800       100